### ISSUE TITLE
[Not self hosting] Can't create account

### ISSUE THREAD

**Issue by Jake1702** [spamgourmet/spamgourmet#16]
Okay, I know this isn't really the place for this, but seeing as I can't register an account for SG, I also can't register for the forums, so I figured this might be the best way of having attention brought to the issue.

It's the same issue as [here](https://bbs.spamgourmet.com/viewtopic.php?f=4&t=1825&sid=ad98fcc8030108699cce99893ab69daf), which was apparently fixed months ago, but came back. Internal server error when trying to register.

Thanks. :)

**Comment by josiah-hamilton** [comment]
Hey Jake, 

Sorry to have seen this so late. Systemd acts funny every time we upgrade. I used to be able to have the service file for the captcha in a local directory but recently systemd refuses to load service files linked to locations other than /lib/systemd. 
I've moved it. Please let me know if you are able to go through the process now.

**Comment by Jake1702** [comment]
It somehow always comes back around to systemd doesn't it?

Yep, I was able to register. Thank you!

**Comment by josiah-hamilton** [comment]
Excellent! Thank you very much for letting us know. I will go ahead and close this.
