### ISSUE TITLE
spamgourmet evolution - countermeasures to increasing blacklisting

### ISSUE THREAD

**Issue by vasile-gh** [spamgourmet/spamgourmet#20]
The reality is that more and more lists flag spamgourmet as "disposable" although its intent here is not really that. Because these lists rely on the mx records to identify spamgourmet domains we cannot hide "private" domains - I have a private one and it's just as unusable as the known ones, because my MX must point to spamgourmet.

I think in the long run spamgourmet is going to be less and less usable so I have been thinking of what could we do about it.

My proposal would be to:
- "dockerize" spamgourmet and provide simple step by step instructions on how to install and configure the domain so it can work - this would include private certificate-based access to the spamgourmet clone site so only the owner and people designated by him can even see it's a spamgourmet clone
- investigate enabling ARC for the clones - this would make mail delivery a lot more reliable
- support options would need to be discussed, but I guess whoever is able to clone spamgourmet should be able to live without their hand being held...

**Comment by mikedlr** [comment]
@josiah-hamilton great to hear from you. There was some fear that something bad had happened.  I think I'd like to get a clear way to have direct contact -  could you perhaps connect with [me on LinkedIn](https://www.linkedin.com/in/mikedlr/) so we could exchange phone numbers? 

The "testing code in the production directory" sounds incredibly valuable.  I think we need to get an agreed and trusted group of people who can view at least some of the stuff on the production server which isn't published and can go through it making as public as it safely can be.  There's some discussion already in [issue 19](https://github.com/spamgourmet/spamgourmet/issues/19)  where I think some comment about what would be helpful for you in future and how much you can engage would be good. 

Dockerization - I think this is the only way to go practically - we need to have a quite specific development and runtime environment available.  I've done this before and had started to work on it a bit but not sure about having enough time given the state of the public code.  It might be good to have a live video call for a mob session with a bunch of us and have a start at doing that?

@eegeeZA are you around and would you join something like that

**Comment by eegeeZA** [comment]
I have tried with limited success having some account created too. I remember being told by one website's support that because [block-disposable-email.com](http://www.block-disposable-email.com/cms/try/) listed spamgourmet as a disposable provider, they would not accept my email. I opted to using my ISPs email address and forwarding that to my main email as a workaround.

@mikedlr I'm on board for going the Docker approach. If we can get the code running there, it will be a much smaller hurdle for others to run the code. Reached out on LinkedIn for if you manage to get that mob session going.

**Comment by josiah-hamilton** [comment]
> @josiah-hamilton great to hear from you. There was some fear that something bad had happened. I think I'd like to get a clear way to have direct contact - could you perhaps connect with [me on LinkedIn](https://www.linkedin.com/in/mikedlr/) so we could exchange phone numbers?
> 
> The "testing code in the production directory" sounds incredibly valuable. I think we need to get an agreed and trusted group of people who can view at least some of the stuff on the production server which isn't published and can go through it making as public as it safely can be. There's some discussion already in [issue 19](https://github.com/spamgourmet/spamgourmet/issues/19) where I think some comment about what would be helpful for you in future and how much you can engage would be good.
> 
> Dockerization - I think this is the only way to go practically - we need to have a quite specific development and runtime environment available. I've done this before and had started to work on it a bit but not sure about having enough time given the state of the public code. It might be good to have a live video call for a mob session with a bunch of us and have a start at doing that?
> 
> @eegeeZA are you around and would you join something like that

Mike, I wasn't able to find you on linked-in, so I sent you contact info on bbs. Would you please check that so we can open communications?
