### ISSUE TITLE
captcha service crashes  - registration fails

### ISSUE THREAD

**Issue by mikedlr** [spamgourmet/spamgourmet#25]
The captcha service on spamgourmet.com has been failing and has caused the registration to fail. This has simply been restarted but we need to recover more information if it happens agian

**Comment by mikedlr** [comment]
Discussion related to this has been in [this thread on the BBS](https://bbs.spamgourmet.com/viewtopic.php?f=4&t=1825&sid=8e0921f07872bacf6806bb48e3e59e75&start=15).

**Comment by fredericmora** [comment]
Will do.

**Comment by caspertone2003** [comment]
Tried to register, captcha is not shown.
image links to https://www.spamgourmet.com/captcha/capVKI93w2n.jpg

The outcome from that link into a browser tab states "the image cannot be displayed because it contains errors"

Registration not possible as captcha not shown.

Have to bbs user so will not report there

**Comment by caspertone2003** [comment]
By the way, anyone in this git has access to the online spamgourmet.com operation/administration??

**Comment by mikedlr** [comment]
@caspertone2003  We have access to the people who have access (and they have access to these git repos if they need). The new admins are aware of the fact that there's currently a problem with registration to the service but we are having some issues with deploying the fix and it will hopefully get done once we work out and have time to complete the work. Afraid there's obviously been a bit of loss of familiarity with how everything works, but we believe nothing which is too major a problem.

**Comment by mikedlr** [comment]
@caspertone2003 there's some messaging on signal.  Do you use LinkedIN?  If so contact me as [mikedlr](https://www.linkedin.com/in/mikedlr/).

**Comment by caspertone2003** [comment]
@mikedlr 
wish to preserve my privacy... telegram helps, signal and linkedin do not

**Comment by 89z** [comment]
https://github.com/spamgourmet/spamgourmet/issues/31

**Comment by mikedlr** [comment]
We've now put an improved captcha service which should fix that problem and I have just managed to sign up for a new account so now just need to watch the long term stability to see that everything is working long term.

**Comment by mikedlr** [comment]
@caspertone2003 I just want to follow up on our discussion since this is the current place where I have contact with you. 

Currently there are few and specific reasons to have a back channel. Approximately

a) specific administrative tasks on the main servers - only a very small number of admins
b) personal data (e.g. real email addresses and other stuff in the database) - currently only small number of admins and will only be shared with known identified people who agree to protect it
c) some very limited security through obscurity stuff, mostly with the aim of getting rid of it. 

There are some other things about setting up the project which are currently held in private for little particular reason but where we're aiming to open up as much as reasonable. There are also some things, such as plans to improve some legal issues that sit with the admins but aren't really part of the public spamgourmet project even if we want to support the admins as much as possible with them. 

Everything else related to the public spamgourmet project is currently either in GitHub or discussed on the Spamgourmet BBS. 

I think that, for people that want to cooperate but don't want their personal identity known, GitHub should be the correct way to work. Code or configuration change requests from unknown people can potentially be a bit problematic and so should normally have public review no matter what. Personal administration requests should go through normal spamgourmet support channels such as the BBS. 

Is there anything that you would lose or that would stop you collaborating with the project if you don't have telegram communication with people but do have github and the BBS? If so, would access to private tickets in GitHub solve that?

**Comment by caspertone2003** [comment]
> We've now put an improved captcha service which should fix that problem and I have just managed to sign up for a new account so now just need to watch the long term stability to see that everything is working long term.

Thanks, tested, works!

**Comment by caspertone2003** [comment]
> @caspertone2003 I just want to follow up on our discussion since this is the current place where I have contact with you.

Thanks for the panoramic answer. See bellow.

> Is there anything that you would lose or that would stop you collaborating with the project if you don't have telegram communication with people but do have github and the BBS? If so, would access to private tickets in GitHub solve that?

I made in the 90`s the translation from english to another language of the website. I think that it merits some update ...

I am ready to help on this, but, would prefer to keep which language and my id separated.

I am not aware of the works of private tickets. If they are not open to general read, I would be happy to use that channel.

Best,
CT

**Comment by mikedlr** [comment]
@caspertone2003 we had a discussion through this - there are some problems with using private tickets which won't be resolved at least until we get enterprise features from GitHub and maybe not fully then. Our opinion for now is that if contributing with your current GitHub account would give away too much we suggest registering a separate GitHub account solely for contributing to spamgourmet and working with that account as normal on the spamgourmet public repositories. 

Would that be a solution which would work for you? If not, then please open a separate new ticket with discussion of what mechanisms would and wouldn't work.

**Comment by mikedlr** [comment]
The sign up seems to have been stable since fixes were applied. I'm closing this ticket as resolved. 

In case of future problems that seem to need development work it's probably best to open a new issue ticket here on GitHub.
