### ISSUE TITLE
Captcha image leads to 443 forbidden

### ISSUE THREAD

**Issue by 89z** [spamgourmet/spamgourmet#31]
if you try to make a new account, it takes you to this page

https://www.spamgourmet.com/index.pl

but the image is broken

**Comment by jgonggrijp** [comment]
Thanks for reporting.

I suspect that page looks different for people who already have an account. Please share a screenshot!

**Comment by jgonggrijp** [comment]
Ah, so it is the captcha that is not working! This might be a duplicate of #25, but I'll leave it open just in case it is subtly different.

**Comment by mikedlr** [comment]
We now believe this is fixed. We had a problem with permissions following symlinks. See for example

https://unix.stackexchange.com/questions/20993/symbolic-link-not-allowed-or-link-target-not-accessible-apache-on-centos-6

**Comment by mikedlr** [comment]
Close this and we'll wait for stability verification in #25
