### ISSUE TITLE
Is this the recent code from josh?

### ISSUE THREAD

**Issue by Kettenknecht** [spamgourmet/spamgourmet#7]
Is this the recent code from josh, or is this the old one, decribed in https://bbs.spamgourmet.com/viewtopic.php?f=2&t=1733&p=7928&hilit=delete+user&sid=e5541007ed12439c96a3af3d11c31e44#p7928

I think it is the old one, because the password field in db has still the length of fifty in this code.

**Comment by jgonggrijp** [comment]
@Kettenknecht This repo is an import from the Sourceforge SVN repo, together with a patch (66dba36e9ac9e642e281) that [josh described on the bbs](https://bbs.spamgourmet.com/viewtopic.php?f=5&t=1785#p8200) and some additional documentation by several people including myself.

Judging from the bbs post you linked to, josh was already locked out of Sourceforge at the time of the doubling of the password length. So it is almost certain missing in this repo.

Thanks for bringing this to our attention. Would you mind submitting a pull request with the missing patch?

**Comment by Kettenknecht** [comment]
In http://www.spamgourmet.com/sg.tgz you find a more recent db dump. The tar file is from 2018, so maybe more recent than the sf repo. But, if josiah joined the team, an actual thrustworthy codebase should not be a problem anymore.

**Comment by eegeeZA** [comment]
Will wait for some direction from @josiah-hamilton

**Comment by josiah-hamilton** [comment]
The filesystem entry I see for that file is below. The account wasn't Josh, but he usually liked to do things as the spamgourmet user. 
I can crack it open and take a look, but you've probably done that by now. In early 2018 we didn't talk about spamgourmet much so I wouldn't have any memory context for this upload.
Thanks for having me on board!

```
root@gourmet7:/home/spamgourmet/web/html# ls -l sg.tgz
-rw-r--r-- 1 spamgourmet spamgourmet 9441219 Feb 25  2018 sg.tgz
```
