### ISSUE TITLE
rename spamgourmet-clone to spamgourmet

### ISSUE THREAD

**Issue by mikedlr** [spamgourmet/spamgourmet#9]
If we agree that spamgourment code primary development should be here then we should rename spamgourmet-clone to spamgourment to avoid future confusion.  There needs to be a small amount of warning to avoid confusion, and I'd like explicit agreement from @josiah-hamilton and @eegeeZA that this is the right thing to do.  

Both of you okay with this?

**Comment by josiah-hamilton** [comment]
Mike, that sounds good to me. I really appreciate your keeping everything together. 
I should be getting emails from github again :)

**Comment by eegeeZA** [comment]
Sounds good to me too. Based on #7, we will just need to update with the diff of the latest source code. I should have time to do that during the course of the week and create PR for it.

**Comment by mikedlr** [comment]
Okay;  this repo is probably not in that much use and github provides some automatic redirection in the case of a rename, still this can be a disruptive action and we should start to act like a reasonably stable project people can rely on.  For this reason I'd like to schedule it.  

Current proposal, 12:00 UTC on 2020/03/18.  I will go ahead and rename the repo at that time.  Users are recommended to have most of their work committed and /or pushed at that time.

**Comment by mikedlr** [comment]
Some delay on this due to some personal issues today.  I'm going to do this in about 1 1/2 hours at 18:00 UTC.

**Comment by mikedlr** [comment]
Rename is now complete.  I have also changed the comment on the repo (better suggestions appreciated).
